"""Add reminders notifications and email delivery

Revision ID: 77e493e1d9d8
Revises: 6231de56306e
Create Date: 2026-09-19 13:16:13.994835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e493e1d9d8'
down_revision: Union[str, Sequence[str], None] = '6231de56306e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('interview', 'follow_up', 'custom', name='reminder_kind', native_enum=False, create_constraint=True), server_default='custom', nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('scheduled', 'fired', 'cancelled', name='reminder_status', native_enum=False, create_constraint=True), server_default='scheduled', nullable=False),
    sa.Column('send_email', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminders_owner_application_remind_at', 'reminders', ['user_id', 'application_id', 'remind_at', 'id'], unique=False)
    op.create_index('ix_reminders_status_remind_at', 'reminders', ['status', 'remind_at', 'id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('reminder_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reminder_id', name='uq_notifications_reminder_id')
    )
    op.create_index('ix_notifications_application_id', 'notifications', ['application_id'], unique=False)
    op.create_index('ix_notifications_owner_created', 'notifications', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_notifications_owner_read', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('email_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'sent', 'failed', 'cancelled', name='email_delivery_status', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lease_token', sa.String(length=36), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='ck_email_deliveries_attempts_nonnegative'),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', name='uq_email_deliveries_notification_id')
    )
    op.create_index('ix_email_deliveries_status_lease', 'email_deliveries', ['status', 'lease_until'], unique=False)
    op.create_index('ix_email_deliveries_status_next_attempt', 'email_deliveries', ['status', 'next_attempt_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_deliveries_status_next_attempt', table_name='email_deliveries')
    op.drop_index('ix_email_deliveries_status_lease', table_name='email_deliveries')
    op.drop_table('email_deliveries')
    op.drop_index('ix_notifications_owner_read', table_name='notifications')
    op.drop_index('ix_notifications_owner_created', table_name='notifications')
    op.drop_index('ix_notifications_application_id', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_reminders_status_remind_at', table_name='reminders')
    op.drop_index('ix_reminders_owner_application_remind_at', table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('notification_settings')
    # ### end Alembic commands ###
